style: github
template: CHANGELOG.tpl.md

info:
  title: CHANGELOG
  repository_url: https://github.com/digital-land/planning-application-data-specification
options:
  commits:
    filters:
      Type:
        - spec
        - app
        - tool
        - fix
        - docs
        - req
  commit_groups:
    title_maps:
      spec: "ğŒ­ Model changes"
      app: "ğŸ‘·â€â™€ï¸ Application changes"
      tool: "âš’ï¸ Tooling"
      fix:  "ğŸ› Bug Fixes"
      docs: "ğŸ“š Documentation"
      req: "ğŸ“„ Planning requirement"
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
